services:
  db:
    container_name: agora_db
    build:
      context: ./
      dockerfile: ./docker/mariadb/Dockerfile
    # TODO(srvariable): **Enhancement** instead of keeping these variables
    # in env, use Docker Secrets + Docker Swarm. https://docs.docker.com/engine/swarm/secrets/
    environment:
      MYSQL_DATABASE: ${DB_NAME:-agora}
      MYSQL_USER: ${DB_USER_NAME:-agorauser}
      MYSQL_PASSWORD: ${DB_USER_PASS:-agorapass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
    networks:
      - agora
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    container_name: agora_backend
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_CONNECTION: ${DB_CONNECTION:-mariadb}
      DB_DATABASE: ${DB_DATABASE:-agora}
      DB_USERNAME: ${DB_USER_NAME:-agorauser}
      DB_PASSWORD: ${DB_USER_PASS:-agorapass}
    volumes:
      - backend_data:/var/www/html
    networks:
      - agora
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: agora_frontend
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    networks:
      - agora
    volumes:
      - frontend_data:/agora/dist
    # After the build is done, we don't need the container anymore
    restart: no

  server:
    container_name: agora_server
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_data:/var/www/frontend
      - backend_data:/var/www/html
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/default.conf:/etc/nginx/default.conf
      #- certbot_data:/var/www/certbot
      #- letsencrypt_data:/etc/letsencrypt
    networks:
      - agora
    restart: unless-stopped

  ## This will be useful when we have a domain, so we can generate certificates using Let's Encrypt
  #certbot:
  #  container_name: agora_certbot
  #  build:
  #    context: ./
  #    dockerfile: ./docker/certbot/Dockerfile
  #  volumes:
  #    - certbot_data:/var/www/certbot
  #  # This might be changed to `unless-stopped` if we renew certificates
  #  restart: no

volumes:
  db_data:
  frontend_data:
  backend_data:
  #certbot_data:
  #letsencrypt_data:

networks:
  agora:
    driver: bridge
