spring.application.name=votations

# MariaDB Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/agora}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:agorauser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:agorapass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Blockchain Configuration
blockchain.contract.address=${WEB3J_CONTRACT_ADDRESS:0x5FbDB2315678afecb367f032d93F642f64180aa3}
web3j.client-url=${WEB3J_CLIENT_URL:http://localhost:8545}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true