server {
	listen 80;
	server_name newagora.es www.newagora.es localhost;

	location / {
		return 301 https://$host$request_uri;
	}

	location /.well-known/acme-challenge {
		root /var/www/certbot;
	}
}

server {
	listen 443 ssl;
	server_name newagora.es www.newagora.es localhost;

	#ssl_certificate /etc/ssl/certs/fullchain.pem;
	#ssl_certificate_key /etc/ssl/private/privkey.pem;

    # Generados local (para pruebas)
    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    # AUTENTICACIÓN POR CERTIFICADO
    ssl_client_certificate /etc/nginx/certs/fnmt-chain.pem;
    ssl_verify_client optional;
    ssl_verify_depth 2;

	root /var/www/frontend;
	index index.html;

	location / {
        root /var/www/frontend;
        index index.html;
		try_files $uri $uri/ /index.html;
	}

    location /api/ {
        alias /var/www/html/public/;
        index index.php;

        try_files $uri $uri/ @laravel;

        location ~ \.php$ {
            fastcgi_pass backend:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            include fastcgi_params;
            
            fastcgi_param HTTPS on;
            fastcgi_param REQUEST_URI $request_uri;
        }
    }

    location @laravel {
        fastcgi_pass backend:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param HTTPS on;
        fastcgi_param REQUEST_URI $request_uri;
    }
}
