CREATE TABLE IF NOT EXISTS auditory(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    action VARCHAR(50) NOT NULL,
    description TEXT,
    txHash VARCHAR(130),
    blockHash VARCHAR(130),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_AUDITORY_userId FOREIGN KEY(userId) REFERENCES user(id),
    CONSTRAINT FK_AUDITORY_blockHash FOREIGN KEY(blockHash) REFERENCES block(hash)
);