CREATE TABLE IF NOT EXISTS auditory(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    action VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT,

    CONSTRAINT FK_AUDITORY_userId FOREIGN KEY(userId) REFERENCES user(id)
);
