CREATE TABLE IF NOT EXISTS vote(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    voteHash VARCHAR(130) NOT NULL UNIQUE,
    votationId INT NOT NULL,
    partyId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    municipalityId INT NOT NULL,

    CONSTRAINT FK_VOTE_votationId FOREIGN KEY(votationId) REFERENCES votation(id),
    CONSTRAINT FK_VOTE_partyId FOREIGN KEY(partyId) REFERENCES party(id),
    CONSTRAINT FK_VOTE_municipalityId FOREIGN KEY(municipalityId) REFERENCES municipality(id)
);
