CREATE TABLE IF NOT EXISTS vote(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    voteHash VARCHAR(130) NOT NULL UNIQUE,
    votationId INT NOT NULL,
    partyId INT NOT NULL,
    municipalityId INT NOT NULL,
    blockHash VARCHAR(130) NOT NULL,
    txHash VARCHAR(130) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_VOTE_votationId FOREIGN KEY(votationId) REFERENCES votation(id),
    CONSTRAINT FK_VOTE_partyId FOREIGN KEY(partyId) REFERENCES party(id),
    CONSTRAINT FK_VOTE_municipalityId FOREIGN KEY(municipalityId) REFERENCES municipality(id),
    CONSTRAINT FK_VOTE_blockHash FOREIGN KEY(blockHash) REFERENCES block(hash)
);