CREATE TABLE IF NOT EXISTS vote_intent(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    voteHash VARCHAR(130) NOT NULL UNIQUE,
    votationId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_VOTE_INTENT_userId FOREIGN KEY(userId) REFERENCES user(id) ON DELETE CASCADE,
    CONSTRAINT FK_VOTE_INTENT_votationId FOREIGN KEY(votationId) REFERENCES votation(id) ON DELETE CASCADE
);
