CREATE TABLE IF NOT EXISTS votation_party(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    votationId INT NOT NULL,
    partyId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(votationId, partyId),
    CONSTRAINT FK_VOTATION_PARTY_votationId FOREIGN KEY(votationId) REFERENCES votation(id) ON DELETE CASCADE,
    CONSTRAINT FK_VOTATION_PARTY_partyId FOREIGN KEY(partyId) REFERENCES party(id) ON DELETE CASCADE
);