CREATE TABLE IF NOT EXISTS participation(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    votationId INT NOT NULL,

    CONSTRAINT FK_PARTICIPATION_userId FOREIGN KEY(userId) REFERENCES user(id),
    CONSTRAINT FK_PARTICIPATION_votationId FOREIGN KEY(votationId) REFERENCES votation(id)
);
