services: 
  node1: 
    image: hyperledger/besu:latest 
    container_name: besu-node1 
    volumes: 
      - ./genesis.json:/genesis.json 
      - ./Node-1/data:/opt/besu/data 
      - ./static-nodes.json:/opt/besu/data/static-nodes.json 
    ports: 
      - "8545:8545" 
      - "30303:30303" 
      #Eth por convención utiliza estos puertos 
    command: > 
      --data-path=/opt/besu/data 
      --genesis-file=/genesis.json 
      --rpc-http-enabled 
      --rpc-http-api=ETH,NET,QBFT,WEB3 
      --host-allowlist="*" 
      --rpc-http-cors-origins="all" 
      --p2p-port=30303
      --nat-method=DOCKER 
      --profile=ENTERPRISE 
    networks: 
      - besu-network

  node2: 
    image: hyperledger/besu:latest 
    container_name: besu-node2 
    volumes: 
      - ./genesis.json:/genesis.json 
      - ./Node-2/data:/opt/besu/data 
      - ./static-nodes.json:/opt/besu/data/static-nodes.json 
    command: > 
      --data-path=/opt/besu/data 
      --genesis-file=/genesis.json 
      --p2p-port=30304 
      --rpc-http-enabled 
      --rpc-http-api=ETH,NET,QBFT,WEB3 
      --host-allowlist="*" 
      --rpc-http-cors-origins="all" 
      --rpc-http-port=8546 
      --nat-method=DOCKER 
      --profile=ENTERPRISE 
    networks: 
      - besu-network

  node3: 
    image: hyperledger/besu:latest 
    container_name: besu-node3 
    volumes: 
      - ./genesis.json:/genesis.json 
      - ./Node-3/data:/opt/besu/data 
      - ./static-nodes.json:/opt/besu/data/static-nodes.json 
    command: > 
      --data-path=/opt/besu/data 
      --genesis-file=/genesis.json 
      --p2p-port=30305 
      --rpc-http-enabled 
      --rpc-http-api=ETH,NET,QBFT,WEB3 
      --host-allowlist="*" 
      --rpc-http-cors-origins="all" 
      --rpc-http-port=8547 
      --nat-method=DOCKER 
      --profile=ENTERPRISE 
    networks: 
    - besu-network

  node4: 
    image: hyperledger/besu:latest 
    container_name: besu-node4 
    volumes: 
      - ./genesis.json:/genesis.json 
      - ./Node-4/data:/opt/besu/data 
      - ./static-nodes.json:/opt/besu/data/static-nodes.json 
    command: > 
      --data-path=/opt/besu/data 
      --genesis-file=/genesis.json 
      --p2p-port=30306 
      --rpc-http-enabled 
      --rpc-http-api=ETH,NET,QBFT,WEB3 
      --host-allowlist="*" 
      --rpc-http-cors-origins="all" 
      --rpc-http-port=8548 
      --nat-method=DOCKER 
      --profile=ENTERPRISE 
    networks: 
      - besu-network 
      
networks: 
  besu-network: 
    driver: bridge