apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: besu-monitor
  namespace: besu
  labels:
    release: monitoring
spec:
  jobLabel: besu
  selector:
    matchLabels:
      app: besu-node
  namespaceSelector:
    matchNames:
      - besu
  endpoints:
  - port: metrics
    interval: 15s