apiVersion: v1
kind: Secret
metadata:
  name: besu-node-keys
  namespace: besu
type: Opaque
data:
  # Estas clave se sacan del siguiente comando: echo -n "Clave privada sin 0x" | base64
  key-0: NTMwNTE2MDk2NDEzZTcwNDg3MDg2NzI3YzQ1MzE4MGI2MDFiODFkODc0MWZmOWIzMTRjODRlOTQ2M2M4MmNiYg==
  key-1: YjcyYzIzNTA1M2NmOWI4NGY2NGQxNDI0ZTEyNGFlYzI1Yzk2ZWMwZTUyOWE5ZWMxNTc1OGZiYTI3YmU3NDAxYg==
  key-2: ZTNjMTUzNDUwMTUwMjg5YzIwZmFjMTc2MzE3OTk1NjJlZmZhYjY5NjhiZmY2NjU5Y2M1ODZjZGRlZWRmMGU1NQ==
  key-3: ZDQ2YzgyOTZjNDhlYWY4ZGJiNjE3YjMyZTg2ZjVjYzMxZDU5NzVmNjczMGNhZmVmNWIwMDAxY2MxMzQ4NDhhOQ==