apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: besu
spec:
  serviceName: "besu-service"
  replicas: 4
  selector:
    matchLabels:
      app: besu-node
  template:
    metadata:
      labels:
        app: besu-node
    spec:
      containers:
      - name: besu-node
        image: hyperledger/besu:latest
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["/bin/sh", "-c"]
        args:
          - |
            POD_ID=${HOSTNAME##*-}

            echo "Resolviendo IPs de los compañeros..."
            #Fix: esperar a que los 4 DNS de K8s existan (bucle hasta que resuelva antes de lanzar BESU)
            until \
              IP0=$(getent hosts besu-0.besu-service | awk '{ print $1 }') && [ ! -z "$IP0" ] && \
              IP1=$(getent hosts besu-1.besu-service | awk '{ print $1 }') && [ ! -z "$IP1" ] && \
              IP2=$(getent hosts besu-2.besu-service | awk '{ print $1 }') && [ ! -z "$IP2" ] && \
              IP3=$(getent hosts besu-3.besu-service | awk '{ print $1 }') && [ ! -z "$IP3" ]; \
            do
              echo "Esperando a que todos los pods tengan IP..."
              sleep 2
            done

            # FIX: Definir los 4 bootnodes con sus nombres DNS de K8s
            BOOTNODES="enode://2cf4152de894bd21f2973f6c2d697c07b7435dfbb03f5dbca7d149e79eb73d696c4991729ae8100090ddf9894033b3b911569822aaff9067fa9f80e2fd6f63c4@$IP0:30303,enode://5a9a62374425ece782d9184f1d1098d07525d72c3cf52d37033dbe447268b291e19f6bfbcd0aa7bb8684e6a7017e0084ffadb9d13c4fda7ba5d1e61815ecc3cf@$IP1:30303,enode://7c43af68167e48fce29addba8531b180381cb9f45bb9e165cfa787c2b8a96f4dd4ab84e8281813112507ce84608932e44950d4074496bae9a54f6f3e6a72a152@$IP2:30303,enode://4f4e3a58f5a9577447265db4454cd661a4dd23656e59ce60b8ab149e35ee0647e432953d43ef6b10be4ce38562a2829da692fead17fac7ebde1c441377e5d772@$IP3:30303"

            echo "Todas las IPs resueltas. Lanzando Besu..."

            # Lanzamos Besu apuntando directamente al archivo del Secret
            besu --data-path=/opt/besu/data \
            --genesis-file=/etc/besu/genesis.json \
            --node-private-key-file=/opt/besu/keys/key-$POD_ID \
            --bootnodes=$BOOTNODES \
            --rpc-http-enabled=true \
            --rpc-http-api=ETH,NET,QBFT,WEB3 \
            --rpc-http-host=0.0.0.0 \
            --rpc-http-cors-origins="*" \
            --p2p-enabled=true \
            --p2p-host=$POD_IP \
            --p2p-interface=0.0.0.0 \
            --discovery-enabled=true \
            --host-allowlist="*" \
            --profile=ENTERPRISE
        ports:
        - containerPort: 30303
          name: p2p
        - containerPort: 8545
          name: rpc
        volumeMounts:
        - name: genesis-vol
          mountPath: /etc/besu
        - name: data-vol
          mountPath: /opt/besu/data
        - name: node-key-vol # The name is the same than the other volumes of the bottom
          mountPath: /opt/besu/keys
      volumes:
      - name: genesis-vol
        configMap:
          name: besu-genesis-config
      - name: node-key-vol
        secret:
          secretName: besu-node-keys
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
